moco/rails/config/routes.rb
Moco::Application.routes.draw do

  resources :presentations do
    member do
      get 'status'
      post 'slideUpdate'
      get 'control'
      get 'upload'
      put 'file_upload'
    end
  end

  devise_for :users

  root :to => redirect("/users/sign_in")

  match '/me' => "presentations#index", :as => :user_root

end

moco/rails/app/models/presentation.rb
class Presentation < ActiveRecord::Base


end

moco/rails/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

moco/rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :prepare_for_mobile

  def mobile_device?
    if session[:mobile_param]
      session[:mobile_param] == "1"
    else
      request.user_agent =~ /Mobile|webOS/
    end
  end
  helper_method :mobile_device?

  def prepare_for_mobile
    session[:mobile_param] = params[:mobile] if params[:mobile]
    request.format = :mobile if mobile_device?
  end
end

moco/rails/app/controllers/presentations_controller.rb
require 'digest/md5'
require 'pusher'

Pusher.app_id = '666'
Pusher.key = 'ea86e9b8c9fefebb4468'
Pusher.secret = 'On Her Majesty\'s Secret Service'

class PresentationsController < ApplicationController

  # user must be logged in
  before_filter :check_login

  after_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Request-Method'] = '*'
  end

  def check_login
	  if not user_signed_in? # redirect to login
		  redirect_to "/users/sign_in" and return
	  end
  end

  # GET /presentations
  # GET /presentations.json
  def index
    @presentations = Presentation.where(:owner => current_user.id).all

    respond_to do |format|
      format.html # index.html.erb
      format.mobile
      format.json { render json: @presentations }
    end
  end

  # GET /presentations/1
  # GET /presentations/1.json
  def show
    @presentation = Presentation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @presentation }
    end
  end

  # GET /presentations/new
  # GET /presentations/new.json
  def new
    @presentation = Presentation.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @presentation }
    end
  end

  # get /presentations/1/edit
  def edit
    @presentation = Presentation.find(params[:id])
  end

  def upload

  end

  def file_upload
    # file handling
    name = params[:presentation][:slide_file].original_filename
    digestName = Digest::MD5.hexdigest(name + current_user.id.to_s + Time.now.to_s ) + ".html"# todo: improve

    file = params[:presentation][:slide_file]
    path = File.join("public/slides", digestName)
    File.open(path, "wb") { |f| f.write(file.read) }
    @notice_msg = "default"

    # js injection
    method = "pusher" # pusher default
    moco_injection = inject(params[:id], method)

    content = File.read(path)
    if content =~ /<\/body>/
      injected = content.gsub(/<\/body>/,  moco_injection)
      File.open(path, "wb") { |f| f.puts injected }
      @notice_msg = "success"
    else # end of the body not found
      @notice_msg = "unable to set up presentation"
    end

    # save presentation
    @presentation = Presentation.find(params[:id])
    @presentation.currentSlide = 0
    @presentation.url = "slides/" + digestName
    @presentation.method = method
    @presentation.save

    redirect_to :action => "index", :notice => @notice_msg
  end

  # POST /presentations
  # POST /presentations.json
  def create
    @presentation = Presentation.new(params[:presentation])
    @presentation.owner = current_user.id

    respond_to do |format|
      if @presentation.save
        format.html { render action: "upload" }
      else
        format.html { render action: "new" }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # put /presentations/1
  # PUT /presentations/1.json
  def update
    @presentation = Presentation.find(params[:id])

    respond_to do |format|
      if @presentation.update_attributes(params[:presentation])
        format.html { redirect_to @presentation, notice: 'Presentation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @presentation = Presentation.find(params[:id])
    @presentation.destroy

    respond_to do |format|
      format.html { redirect_to presentations_url }
      format.json { head :no_content }
    end
  end

  # GET /presentations/1/view
  def view
    @presentation = Presentation.find(params[:id])
    redirect_to @presentation.url
  end

  # GET /presentations/1/control
  def control
     @presentation = Presentation.find(params[:id])
  end

  # post /presentations/1/slideUpdate
  def slideUpdate
    @presentation = Presentation.find(params[:id])

    # check that user is owner of slides
    if current_user.id != @presentation.owner
      Rails.logger.info("FAILDED!")
      @status = "failed"
      render json: {:status => @status}
    end

      Rails.logger.info("SUCCESS!")
    if @presentation.method == "pusher" #pusher controlling
      if params[:cmd] == "next"
        Pusher[@presentation.id.to_s + 'p'].trigger('s-update', {:cmd => 'fwd'})
        @presentation.currentSlide += 1
      elsif params[:cmd] == "prev"
        Pusher[@presentation.id.to_s + 'p'].trigger('s-update', {:cmd => 'bck'})
        @presentation.currentSlide -= 1
      end
    end

    if @presentation.method == "polling" #ajax-polling controlling
      @presentation.currentSlide = params[:slide].to_i
    end
    @presentation.save

    @status = "succeeded"

    render json: { :status => @status }

  end

  # get /presentations/1/status
  def status
    @presentation = Presentation.find(params[:id])
    render json: { :currentSlide => @presentation.currentSlide  }
  end

  # returns js to inject
  def inject(id, method)
    injection = ""
    case method
      when "polling" # plain ajax-polling
        injection = "<script src=\"/assets/moco.js\"></script>
              <script>
                $(document).ready(function() { Moco.init("+ id +",1000); });
              </script></body>"
      when "pusher" # pusher
        injection = "<script src=\"http://js.pusher.com/1.11/pusher.min.js\"></script>
                <script>
                  var pusher = new Pusher('" + Pusher.key + "');
                  var channel = pusher.subscribe('" + id + "p');
                  channel.bind('s-update', function(data) {
                    switch(data.cmd) {
                      case 'fwd':
                        $(\"#jmpress\").jmpress('next');
                        break;
                      case 'bck':
                        $(\"#jmpress\").jmpress('prev');
                        break;
                    };
                  });
                </script>"
    end
    return injection
  end

end

moco/rails/app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

moco/rails/app/helpers/presentations_helper.rb
module PresentationsHelper
end

moco/rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SlideCTRL</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "desktop/application", :media => "all" %>
  <%= javascript_include_tag "desktop/application" %>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
  <div class="container">
  <div class="navbar">
      <div class="navbar-inner">
        <div class="container" style="width: auto;">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">SlideCTRL</a>
          <div class="nav-collapse">
            <ul class="nav">
              <% if not user_signed_in? %>
              <li class="active"><a href="/">Home</a></li>
              <% else %>
              <li class="btn-primary">
                <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
              </li>
            </ul>
            <% end %>
          </div><!-- /.nav-collapse -->
        </div>
      </div><!-- /navbar-inner -->
    </div><!-- /navbar -->

    <section>
      <%= yield %>
    </section>
  </div>

</body>
</html>

moco/rails/app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>
        </title>
        <%= stylesheet_link_tag    "mobile/application", :media => "all" %>
        <%= javascript_include_tag "mobile/application" %>
        <%= csrf_meta_tag %>

    </head>
    <body>
      <%= yield %>
    </body>
</html>

moco/rails/app/views/presentations/_form.html.erb
<%= form_for @presentation do |f| %>
  <% if @presentation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@presentation.errors.count, "error") %> prohibited this presentation from being saved:</h2>

      <ul>
      <% @presentation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="control-group">
    <%= f.label :description, "Description (optional)" %>
    <%= f.text_area :description, :class => "input-xlarge", :rows => "3" %>
  </div>
  <div class="actions">
    <%= f.submit "Proceed", :class => "btn btn-large btn-success"%>
  </div>
<% end %>

moco/rails/app/views/presentations/control.html.erb
<h3>Controller for presentation</h3>

<script type="text/javascript">
  var id = <%= @presentation.id %>;
  var slide = <%= @presentation.currentSlide %>;

  $(document).ready(function(){
    $("#next").click(function() {
      slide++;
      $.ajax({
        type: 'POST',
        url: 'slideUpdate',
        data: 'id='+id+'&slide='+slide,
        success: function(){},
        dataType: 'json'
      }); 
    });
    $("#prev").click(function() {
      slide--;
      $.ajax({
        type: 'POST',
        url: 'slideUpdate',
        data: 'id='+id+'&slide='+slide,
        success: function(){},
        dataType: 'json'
      });
    });
  });

</script>
<div class="row">
<button id="next" class="btn-primary">next slide</button>
<button id="prev" class="btn-primary">previous slide</button>
</div>
<div class="row">
  <%= link_to 'Back', presentations_path %>
</div>

moco/rails/app/views/presentations/control.mobile.erb
        <div data-role="page" data-theme="a" id="control">
            <script type="text/javascript">
                $("#control").live('pageinit', function() {

                   $("#next").live('tap',function(e) {
                        moveNext(e);
                    });

                    $("#previous").live('tap',function(e) {
                        movePrevious(e);
                    });

                    $("#next").click(function (e) {
                        moveNext(e);
                    });

                    $("#previous").click(function (e) {
                        movePrevious(e);
                    });
                });

                function moveNext(e) {
                    e.stopImmediatePropagation();
                    e.preventDefault();
                    
                    updateSlide("next");
                }

                function movePrevious(e) {
                    e.stopImmediatePropagation();
                    e.preventDefault();

                    updateSlide("prev");
                }

                function updateSlide(command) {
                   $.ajax({
                   url: "/presentations/<%= @presentation.id %>/slideUpdate",
                          type: "POST",
                          data: {
                          id: <%= @presentation.id %>, 
                                   cmd: command},
                          headers: {
                            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
                          },
                          success: function(resp){}
                      });
                }
            </script>
            <div data-theme="b" data-role="header">
                <h3 id="control-header">
                <%= @presentation.name %>
                </h3>
            </div>
            <div data-role="content">
                <div class="ui-grid-a">
                    <div class="ui-block-a">
                        <a id="previous" data-role="button" data-transition="fade" href="page1" data-icon="arrow-l" data-iconpos="left">
                            Previous
                        </a>
                    </div>
                    <div class="ui-block-b">
                        <a id="next" data-role="button" data-transition="fade" href="page1" data-icon="arrow-r" data-iconpos="left">
                            Next
                        </a>
                    </div>
                </div>
            </div>
            <div data-theme="a" data-role="footer">
                <h3>
                    Menu
                </h3>
                <div data-role="navbar" data-iconpos="left">
                    <ul>
                        <li>
                        <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
                        </li>
                        <li>
                        <%= link_to 'My presentations', presentations_path, :rel => "external" %> 
                        </li>
                    </ul>
                </div>
            </div>
        </div>

moco/rails/app/views/presentations/edit.html.erb
<h1>Editing presentation 
</h1>

<%= render 'form' %>

<%= button_to 'Delete', presentation_path, :method => :delete, :confirm => "Are you sure?", :class => 'btn btn-small btn-danger' %>
<%= link_to 'Back', presentations_path, :class => "btn" %>

moco/rails/app/views/presentations/index.html.erb
<h1>My presentations <%= link_to 'New Presentation', new_presentation_path, :class => "btn btn-success btn-large" %> </h1>
<br/>
<p id="notice"><%= flash[:notice] %></p>

<div class="row-fluid">
<% @presentations.each do |presentation| %>
      <div class="span3">
        <div class="thumbnail well">
          <div class="caption">
            <h4><%= presentation.name %></h4>
            <p><%= presentation.description %></p>
            <p>
              <% if not mobile_device? %>
                <%= link_to 'View', presentation.url, :class => "btn btn-info" %>
                <%= link_to 'Edit', edit_presentation_path(presentation), :class => "btn" %>
              <% else %>
                <%= link_to 'Control', control_presentation_path(presentation), :class => "btn btn-primary" %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
<% end %>
</div>
<br />

moco/rails/app/views/presentations/index.mobile.erb
        <div data-role="page" data-theme="a" id="index" data-url="/presentations/#">
            <div data-theme="a" data-role="header">
                <h3>
                    SlideCTRL.com
                </h3>
            </div>
            <div data-role="content">
                <ul data-role="listview" data-divider-theme="a" data-inset="true">
                    <li data-role="list-divider" role="heading">
                        My Presentations
                    </li>
                    <% @presentations.each do |presentation| %>
                      <li data-theme="a" data-icon="arrow-r">
                      <%= link_to presentation.name, control_presentation_path(presentation), :rel => "external", :"data-transition" => "slide" %>
                      </li>
                    <% end %>
                    </ul>
            </div>
            <div data-theme="a" data-role="footer">
                <h3>
                    Menu
                </h3>
                <div data-role="navbar" data-iconpos="left">
                    <ul>
                        <li>
                        <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

moco/rails/app/views/presentations/landing.html.erb
<div class="form-horizontal well">
<%= form_for("user", :url => user_session_path) do |f| %>
  <%= f.text_field :email, :class => "input-medium" %>
  <%= f.password_field :password, :class => "input-small" %>
  <%= f.check_box :remember_me %>
  <%= f.label :remember_me %>
  <%= f.submit 'Sign in', :class => "btn btn-primary" %>
  <%= link_to "Forgot your password?", new_password_path('user') %>
<% end %>
</div>

moco/rails/app/views/presentations/new.html.erb
<h1>Step 1: Fill in the basics</h1>

<%= render 'form' %>

<%= link_to 'Back', presentations_path, :class => "btn btn-small" %>

moco/rails/app/views/presentations/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Owner:</b>
  <%= @presentation.owner %>
</p>

<p>
  <b>Name:</b>
  <%= @presentation.name %>
</p>

<p>
  <b>Description:</b>
  <%= @presentation.description %>
</p>

<p>
  <b>Currentslide:</b>
  <%= @presentation.currentSlide %>
</p>


<%= link_to 'Edit', edit_presentation_path(@presentation) %> |
<%= link_to 'Back', presentations_path %>

moco/rails/app/views/presentations/upload.html.erb
<h1>Step 2: Select file to upload</h1>
<%= form_for @presentation, :url => file_upload_presentation_path(@presentation), :html => {:multipart => true} do |f| %>
  <div class="control-group">
  <label for="upload_file">Select presentation file to upload:</label> 
  <%= f.file_field :slide_file, :class => 'btn' %>
  </div>
  <%= f.submit "Upload" %>
<% end %>